[package]
name = "geph4-client"
version = "4.5.2-alpha.2"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2021"
description="Geph client"
license="GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "geph4client"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
# add icon
embed-resource = "1.5.1"

[dependencies]
anyhow = "1.0.43"
# geph4_protocol={path="../lib/geph4_protocol"}
async-h1= "2.3.2"
bincode = "1.3.3"


# geph4-binder-transport = {path="../geph4-libs/geph4-binder-transport"}
geph4-binder-transport = "0.2"

dirs = "3.0.2" 
ed25519-dalek={ version = "1.0.1", features = ["serde"] }
futures-util= "0.3.17"
hex = "0.4.3"
http-types = "2.12.0"
log = "0.4.14"
once_cell= "1.8.0"
parking_lot = { version = "0.11.2", features = ["serde"] }
rand= "0.7.3"
regex= "1.5.4"
rsa-fdh = "0.5.0"
# sled="0.34"
acidjson= "0.1.0"
scopeguard = "1.1.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
sha2 = "0.9.8"
smol = "1.2.5"
smol-timeout = "0.6.0"
socksv5 = "0.2.0"
sosistab= "0.4.38"
# sosistab={path="../sosistab"}
strsim = "0.10.0"
structopt = "0.3.23"
x25519-dalek={ version = "1.1.1", features = ["serde"] }
chrono = "0.4.19" 
async-net= "1.6.1" 
socket2= "0.3.19"
# aioutils={path="../lib/aioutils"}
treebitmap= "0.4.0"
pnet_packet= "0.27.2"
governor= "0.3.2"
async-dup= "1.2.2"
bytes= { version = "1.1.0", features = ["serde"] }
tap= "1.0.1"
smolscale= "0.3.16"
async-compat= "0.2.1"
im= "15.0.0"
# surf={version="2.2.0", features=["h1-client-rustls"], default-features=false}
event-listener= "2.5.1"
cached= "0.23.0"
rustls= "0.19.1"
webpki-roots= "0.21.1"
strip-ansi-escapes= "0.1.1"

mizaru = "0.1.3"
geph4-aioutils = "0.1.3"
# alloc_geiger = "0.1"

# socks2http
tokio = { version = "1.11.0", features = ["rt","net", "io-util"] }
hyper = { version = "0.14.12", features = ["http1", "client", "server", "tcp", "stream"] }
pin-project = "1.0.8"
http = "0.2.4"
geph4-protocol = "0.2"
psl = "2.0.48"
async-trait = "0.1.51"
tracing = "0.1.26"
env_logger = "0.9.0"
rlimit = "0.6.2"
binary-search = "0.1.2"
fastrand = "1.5.0"

[dependencies.async-tls]
version = "0.11.0"
default-features = false
features = ["client"]
# tracing-flame="0.1"

# tracing-subscriber = "0.2.15"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["minwindef", "mmsystem", "timeapi"] }

[profile.dev]
panic = "abort"
opt-level=1



[profile.release]
panic = "abort"
opt-level=3
debug=0
# lto=true
strip="debuginfo"
